USE TrafficPolice;

CREATE TABLE Model (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Model PRIMARY KEY,
	ID_Manufacter UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Manufacter FOREIGN KEY 
	REFERENCES Manufacter(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	[Name] VARCHAR(255) NOT NULL,
);