USE TrafficPolice;

CREATE TABLE [Owner] (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Owner PRIMARY KEY,
	ID_Car UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Car FOREIGN KEY 
	REFERENCES Car(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
    ID_Driver UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Driver FOREIGN KEY 
	REFERENCES Driver(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	BeginDate DATE NOT NULL,
	EndDate DATE,
);