USE TrafficPolice;

CREATE TABLE Record (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Record PRIMARY KEY,
    ID_Car UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_RecordCar FOREIGN KEY 
	REFERENCES Car(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	Accidents INT NOT NULL
);