USE TrafficPolice;

CREATE TABLE AccidentMember (
	ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_AccidentMember PRIMARY KEY,
	ID_Car UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_AccidentMemberCar FOREIGN KEY 
	REFERENCES Car(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	ID_Accident UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Accident FOREIGN KEY 
	REFERENCES Accident(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
);