USE TrafficPolice;

CREATE TABLE Hijacking (
	ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Hijacking PRIMARY KEY,
	ID_Car UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_HijackingCar FOREIGN KEY 
	REFERENCES Car(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	HijackingDate DATE NOT NULL,
	Hijack BIT NOT NULL,
);