USE TrafficPolice;

CREATE TABLE Driver (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Driver PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
	SurName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	PassportID VARCHAR(255) NOT NULL,
);

ALTER TABLE Driver
ADD CONSTRAINT u_DriverPassportID UNIQUE(PassportID);