USE TrafficPolice;

CREATE TABLE Color (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Color PRIMARY KEY,
    [Name] VARCHAR(255) NOT NULL,
);

ALTER TABLE Color
ADD CONSTRAINT u_ColorName UNIQUE([Name]);