USE TrafficPolice;

CREATE TABLE Car (
	ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Car PRIMARY KEY,
	RegistrationNumber VARCHAR(255) NOT NULL,
	ID_Model UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Model FOREIGN KEY 
	REFERENCES Model(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	ID_Color UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Color FOREIGN KEY 
	REFERENCES Color(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	ReleaseDate DATE NOT NULL,
);

ALTER TABLE Car
ADD CONSTRAINT u_CarRegistrationNumber UNIQUE(RegistrationNumber);