CREATE FUNCTION dbo.fColorID
(
	@ColorName VARCHAR(255)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @ID_Color UNIQUEIDENTIFIER = (SELECT TOP 1 ID FROM Color WHERE [Name]=@ColorName)
	RETURN @ID_Color;
END;