CREATE FUNCTION dbo.fDriverID
(
	@PassportID VARCHAR(255)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @ID_Driver UNIQUEIDENTIFIER = (SELECT TOP 1 ID FROM Driver WHERE PassportID = @PassportID);
	RETURN @ID_Driver;
END;