CREATE FUNCTION dbo.fModelID
(
	@ModelName VARCHAR(255)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @ID_Model UNIQUEIDENTIFIER = (SELECT TOP 1 ID FROM Model WHERE [Name]=@ModelName)
	RETURN @ID_Model;
END;